/* 01: Criação das tabelas */

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11)  NOT NULL
);

CREATE TABLE CARRO (
    ID_CARRO INT NOT NULL PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL
);

CREATE TABLE VENDA (
    ID_VENDA INT NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_CARRO INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_VENDA_CARRO FOREIGN KEY (ID_CARRO)   REFERENCES CARRO (ID_CARRO)
);
