/* 03: Quantidade de vendas do carro Uno por cliente */

SELECT 	CL.ID_CLIENTE,
       	CL.NOME,
       	COUNT(V.ID_VENDA) AS QTDE_VENDAS_UNO
FROM 	CLIENTE CL
	INNER JOIN VENDA V 
		ON V.ID_CLIENTE = CL.ID_CLIENTE
	INNER JOIN CARRO C 
		ON C.ID_CARRO = V.ID_CARRO
WHERE 	C.MODELO = 'UNO'
GROUP BY 
	CL.ID_CLIENTE, CL.NOME
ORDER BY 
	QTDE_VENDAS_UNO DESC;
